//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProg_3___Car_Rental_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int VehicleID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<short> Doors { get; set; }
        public Nullable<int> Emission { get; set; }
        public string FuelType { get; set; }
        public string Gearbox { get; set; }
        public Nullable<short> Seats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
    }
}
